import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { JsonCache } from '../src/cache.mjs';

test('single flight, disk persistence, TTL, ETag, stale fallback and error backoff', async (t) => {
  const dir = await mkdtemp(join(tmpdir(), 'jev-cache-test-'));
  t.after(() => rm(dir, { recursive: true, force: true }));
  let now = 1000, calls = 0;
  let response = () => Response.json({ models: ['new'] }, { headers: { etag: 'v1' } });
  const fetch = async (url, options) => { calls++; return response(options); };
  const opts = { ttl: 100, maxStale: 1000, validate: (v) => Array.isArray(v.models) };
  let cache = new JsonCache(dir, { now: () => now, fetch });
  await Promise.all([cache.get('https://example.com/data', opts), cache.get('https://example.com/data', opts)]);
  assert.equal(calls, 1);
  cache = new JsonCache(dir, { now: () => now, fetch });
  await cache.get('https://example.com/data', opts);
  assert.equal(calls, 1);
  now += 101;
  response = (options) => { assert.equal(options.headers['if-none-match'], 'v1'); return new Response(null, { status: 304 }); };
  assert.equal((await cache.get('https://example.com/data', opts)).stale, false);
  assert.equal(calls, 2);
  now += 101;
  response = () => new Response(null, { status: 429 });
  assert.equal((await cache.get('https://example.com/data', opts)).stale, true);
  await cache.get('https://example.com/data', { ...opts, force: true });
  assert.equal(calls, 3);
  now += 1000;
  await assert.rejects(cache.get('https://example.com/data', opts));
  assert.equal(calls, 3);
});
test('malformed refresh cannot poison last valid cache; cold errors are cached too', async (t) => {
  const dir = await mkdtemp(join(tmpdir(), 'jev-cache-test-'));
  t.after(() => rm(dir, { recursive: true, force: true }));
  let calls = 0;
  const cache = new JsonCache(dir, { fetch: async () => { calls++; return Response.json({ invalid: true }); } });
  const opts = { ttl: 100, maxStale: 1000, validate: () => false };
  await assert.rejects(cache.get('https://example.com/bad', opts));
  await assert.rejects(cache.get('https://example.com/bad', opts));
  assert.equal(calls, 1);
  let now = 1000;
  let invalid = false;
  const second = new JsonCache(dir, { now: () => now, fetch: async () => Response.json(invalid ? { invalid: true } : { models: ['keep'] }) });
  const valid = { ttl: 100, maxStale: 1000, validate: (v) => Array.isArray(v.models) };
  await second.get('https://example.com/refresh', valid);
  now += 101;
  invalid = true;
  const result = await second.get('https://example.com/refresh', valid);
  assert.deepEqual(result.value.models, ['keep']);
  assert.equal(result.stale, true);
});
